language: python
python:
  - "3.6"
addons:
  postgresql: "9.4"
install: pip install -r requirements.txt
before_script:
  - psql -c 'create database jobapplications;' -U postgres
  - python setup.py
script: pytest --cov --cov-config=.coveragerc tests/
